import { Printer, MessageSquare, Target, User } from 'lucide-react';
import type { LoanResult, BorrowerInput } from '@/types';
import { formatINR } from '@/domain/loanEngine';

interface NegotiationCardProps {
  result: LoanResult;
  input: BorrowerInput;
}

export function NegotiationCard({ result, input }: NegotiationCardProps) {
  const card = result.negotiationCard;

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="card p-6 sm:p-8" id="negotiation-card">
      <div className="flex items-start justify-between mb-6 no-print">
        <div className="flex items-center gap-2">
          <MessageSquare className="w-5 h-5 text-plum-500" />
          <h3 className="text-lg font-serif font-semibold text-plum-700">Negotiation Card</h3>
        </div>
        <button onClick={handlePrint} className="btn-secondary flex items-center gap-2 text-sm py-2 px-4">
          <Printer className="w-4 h-4" />
          Print
        </button>
      </div>

      {/* Print-only header */}
      <div className="hidden print:block mb-6">
        <h1 className="text-2xl font-serif font-bold text-plum-700">Borrower Copilot — Negotiation Card</h1>
        <p className="text-sm text-plum-400">Know Before You Owe</p>
      </div>

      {/* Profile summary */}
      <div className="flex items-start gap-3 mb-6 p-4 bg-plum-50/50 rounded-xl">
        <User className="w-5 h-5 text-plum-400 mt-0.5 shrink-0" />
        <div>
          <p className="text-xs font-medium text-plum-400 uppercase tracking-wider mb-1">Borrower Profile</p>
          <p className="text-sm text-plum-700 leading-relaxed">{card.profileSummary}</p>
        </div>
      </div>

      {/* Target numbers grid */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6">
        <div className="p-4 rounded-xl border border-plum-100 bg-white">
          <p className="text-xs text-plum-400 mb-1">Target Rate</p>
          <p className="text-xl font-mono font-bold text-plum-700">
            {(card.targetRate * 100).toFixed(2)}%
          </p>
          <p className="text-[10px] text-plum-300 mt-0.5">Walk in asking for this</p>
        </div>
        <div className="p-4 rounded-xl border border-plum-100 bg-white">
          <p className="text-xs text-plum-400 mb-1">Target EMI</p>
          <p className="text-xl font-mono font-bold text-plum-700">
            {formatINR(card.targetEMI)}
          </p>
          <p className="text-[10px] text-plum-300 mt-0.5">Per month ceiling</p>
        </div>
        <div className="p-4 rounded-xl border border-plum-100 bg-white">
          <p className="text-xs text-plum-400 mb-1">Target Loan Amount</p>
          <p className="text-xl font-mono font-bold text-plum-700">
            {formatINR(card.targetLoanAmount)}
          </p>
          <p className="text-[10px] text-plum-300 mt-0.5">Safe carry limit</p>
        </div>
      </div>

      {/* Talking points */}
      <div>
        <div className="flex items-center gap-2 mb-3">
          <Target className="w-4 h-4 text-plum-500" />
          <p className="text-xs font-medium text-plum-400 uppercase tracking-wider">Talking Points for the Branch</p>
        </div>
        <ol className="space-y-3">
          {card.talkingPoints.map((point, i) => (
            <li key={i} className="flex items-start gap-3">
              <span className="w-6 h-6 rounded-full bg-plum-600 text-cream flex items-center justify-center text-xs font-mono font-bold shrink-0">
                {i + 1}
              </span>
              <p className="text-sm text-plum-600 leading-relaxed pt-0.5">{point}</p>
            </li>
          ))}
        </ol>
      </div>

      {/* Print footer */}
      <div className="hidden print:block mt-8 pt-4 border-t border-plum-100">
        <p className="text-xs text-plum-400">
          Generated by Borrower Copilot · {new Date().toLocaleDateString('en-IN')}
        </p>
      </div>
    </div>
  );
}
